CREATE DATABASE cs550;
USE cs550;
DROP TABLE IF EXISTS `register`;
CREATE TABLE `register`(
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `servername` VARCHAR(255) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `ip` VARCHAR(255) DEFAULT NULL,
  `port` INT(11),
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `peer`;
CREATE TABLE `peer`(
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `peerid` INT(11) DEFAULT NULL,
  `peername` VARCHAR(255) DEFAULT NULL,
  `filename` VARCHAR(255) DEFAULT NULL,
  `filepath` VARCHAR(255),
  `filesize` INT(11),
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


SELECT * FROM register;
SELECT * FROM peer;
