CREATE DATABASE cs550;
USE cs550;
DROP TABLE IF EXISTS `peer`;
CREATE TABLE `peer`(
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `peerid` INT(11) DEFAULT NULL,
  `peername` VARCHAR(255) DEFAULT NULL,
  `filename` VARCHAR(255) DEFAULT NULL,
  `filepath` VARCHAR(255),
  `filesize` INT(11),
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

